spring:  
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userandrole
    username: ${username-test}
    password: ${password-test}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
data: Test data 11
